### ISSUE TITLE
Lacking  gRPC

### ISSUE THREAD

**Issue by JoshuaFox** [GabiAxel/google-cloud-gui#2]
I installed it through npm, but get the following. Should I be installing this myself?  If so, how? (Node v.10.0.0)
```
$ google-cloud-gui 
/usr/local/lib/node_modules/google-cloud-gui/node_modules/grpc/src/grpc_extension.js:55
    throw error;
    ^

Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-linux-x64-glibc
Found: [node-v48-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/usr/local/lib/node_modules/google-cloud-gui/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/usr/local/lib/node_modules/google-cloud-gui/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/google-cloud-gui/node_modules/grpc/src/client.js:37:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)

```

**Comment by GabiAxel** [comment]
I think I got it too when using Node 10, but not 8 (though with 8 I encountered #1). I didn't get to fix it yet, so the most reliable solution I can suggest is to use Yarn.

**Comment by JoshuaFox** [comment]
OK,  switched to 
```
$ node -v
v8.9.4

```
(`yarn global add google-cloud-gui` had failed earlier, but this Node version let me run that.)

However, I still get that gRPC error. 

I also get the error  if I remove this in yarn and then install using  `npm i -g google-cloud-gui`

**Comment by GabiAxel** [comment]
Before you installed it again, did you uninstall it? First ensure it is uninstalled by both npm and Yarn (they install global libraries in different locations, but the symlink to the executable command can only reference one of them, which you can see by running `ls -l /usr/local/bin/google-cloud-gui`), and then try Yarn again.

If that fails too, until we find a proper solution, you can download the repository and build it locally as described at the end of [Development](https://github.com/GabiAxel/google-cloud-gui#development) section.

**Comment by JoshuaFox** [comment]
I succeeded!  I saw my Kinds -- wonderful tool!

Among the tricks I tried was the `--unsafe-perm` parameter.  That may have made the difference

**Comment by JoshuaFox** [comment]
In case this helps others who come after me -- the tool  is installed for me at `~/.nvm/versions/node/v8.9.4/lib/node_modules/google-cloud-gui/`

**Comment by calsmith** [comment]
Same error here, the solutions listed above didn't solve the problem
