### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by vamboda** [GabiAxel/google-cloud-gui#8]
Did run following cmd to install **google-cloud-gui**, 
`npm i -g `google-cloud-gui`

and i am hitting following exception while starting the server:

```
C:\Users\vaboda\AppData\Roaming\npm\node_modules\google-cloud-gui\node_modules\server\server.js:20
const Server = async (...middle) => {
                     ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vaboda\AppData\Roaming\npm\node_modules\google-cloud-gui\src\server.js:3:16)
```

**Comment by vamboda** [comment]
Bummer... node version was 6.0.4. I thought i had updated version. Sorry.
